---
detectors:
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    public_methods_only: true

directories:
  test:
    InstanceVariableAssumption:
      enabled: false
    UncommunicativeMethodName:
      enabled: false
