AllCops:
  Exclude:
    - bin/**/*
    - Gemfile
    - Guardfile
    - Rakefile
    - '*.gemspec'
  TargetRubyVersion: 2.5.3

Style/Documentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80
